//! Differential fuzzing support, shared by the in-tree `arbtest` tests and the
//! `cargo-fuzz` targets. Enabled by the `arbitrary` feature.
//!
//! Two layers keep the runtime honest:
//!
//! - [`differential_expr`] generates a random well-typed expression plus an
//!   environment and asserts the WASM tier agrees with the interpreter oracle.
//! - [`differential_program`] generates a random well-typed, stratifiable
//!   program plus facts and asserts the WASM-backed engine agrees with the
//!   interpreter-backed engine on every relation.
//!
//! A third layer — fuzzing EDB facts against the real `ascent!` macro over the
//! fixed fixtures — lives in the test/fuzz crates (the macro is compile-time,
//! so the *rules* cannot be generated). The fact generators here ([`arb_pairs`]
//! and friends) feed that layer. Transitively, macro ≡ interpreter (fixtures +
//! fact-fuzzing) and interpreter ≡ WASM (program fuzzing) give macro ≡ WASM.

use std::collections::{BTreeSet, HashMap};

use arbitrary::{Result, Unstructured};

use crate::Interpreter;
use crate::eval::{self, Database, EvalError, ExprEval};
use crate::expr::{BinOp, Expr, UnOp};
use crate::ir::{
    AggFunc, Aggregate, Arg, Atom, BodyClause, HeadAtom, Program, RelationDecl, RelationKind, Rule,
};
use crate::value::{Symbol, Type, Value};
use crate::wasm::WasmEval;

/// Maximum expression depth generated by the fuzzers.
const MAX_DEPTH: u32 = 4;

/// A generated set of ground facts: `(relation name, tuple)` pairs.
type Facts = Vec<(String, Vec<Value>)>;

// ----- value / type generators -------------------------------------------

fn arb_type(u: &mut Unstructured) -> Result<Type> {
    Ok(match u.int_in_range(0_u8..=2)? {
        0 => Type::Int,
        1 => Type::Bool,
        _ => Type::Sym,
    })
}

fn arb_value(u: &mut Unstructured, ty: Type) -> Result<Value> {
    Ok(match ty {
        Type::Int => Value::Int(u.int_in_range(-4_i64..=4)?),
        Type::Bool => Value::Bool(u.arbitrary()?),
        Type::Sym => Value::Sym(Symbol(u.int_in_range(0_u32..=2)?)),
    })
}

// ----- expression generation ----------------------------------------------

fn arb_leaf(u: &mut Unstructured, env: &[(Symbol, Type)], want: Type) -> Result<Expr> {
    let candidates: Vec<Symbol> = env
        .iter()
        .filter(|(_, t)| *t == want)
        .map(|(s, _)| *s)
        .collect();
    if !candidates.is_empty() && u.arbitrary()? {
        let idx = u.choose_index(candidates.len())?;
        Ok(Expr::Var(candidates[idx]))
    } else {
        Ok(Expr::Lit(arb_value(u, want)?))
    }
}

fn arb_int_expr(u: &mut Unstructured, env: &[(Symbol, Type)], depth: u32) -> Result<Expr> {
    if u.int_in_range(0_u8..=5)? == 5 {
        let inner = arb_expr(u, env, Type::Int, depth - 1)?;
        return Ok(Expr::Unary(UnOp::Neg, Box::new(inner)));
    }
    let op = *u.choose(&[BinOp::Add, BinOp::Sub, BinOp::Mul, BinOp::Div, BinOp::Rem])?;
    let a = arb_expr(u, env, Type::Int, depth - 1)?;
    let b = arb_expr(u, env, Type::Int, depth - 1)?;
    Ok(Expr::Binary(op, Box::new(a), Box::new(b)))
}

fn arb_bool_expr(u: &mut Unstructured, env: &[(Symbol, Type)], depth: u32) -> Result<Expr> {
    match u.int_in_range(0_u8..=4)? {
        0 => {
            let t = arb_type(u)?;
            let op = if u.arbitrary()? { BinOp::Eq } else { BinOp::Ne };
            let a = arb_expr(u, env, t, depth - 1)?;
            let b = arb_expr(u, env, t, depth - 1)?;
            Ok(Expr::Binary(op, Box::new(a), Box::new(b)))
        }
        1 => {
            let op = *u.choose(&[BinOp::Lt, BinOp::Le, BinOp::Gt, BinOp::Ge])?;
            let a = arb_expr(u, env, Type::Int, depth - 1)?;
            let b = arb_expr(u, env, Type::Int, depth - 1)?;
            Ok(Expr::Binary(op, Box::new(a), Box::new(b)))
        }
        2 => {
            let op = if u.arbitrary()? {
                BinOp::And
            } else {
                BinOp::Or
            };
            let a = arb_expr(u, env, Type::Bool, depth - 1)?;
            let b = arb_expr(u, env, Type::Bool, depth - 1)?;
            Ok(Expr::Binary(op, Box::new(a), Box::new(b)))
        }
        3 => Ok(Expr::Unary(
            UnOp::Not,
            Box::new(arb_expr(u, env, Type::Bool, depth - 1)?),
        )),
        _ => arb_leaf(u, env, Type::Bool),
    }
}

fn arb_expr(u: &mut Unstructured, env: &[(Symbol, Type)], want: Type, depth: u32) -> Result<Expr> {
    if depth == 0 || u.ratio(1_u8, 3_u8)? {
        return arb_leaf(u, env, want);
    }
    match want {
        Type::Sym => arb_leaf(u, env, want),
        Type::Int => arb_int_expr(u, env, depth),
        Type::Bool => arb_bool_expr(u, env, depth),
    }
}

fn arb_expr_and_env(u: &mut Unstructured) -> Result<(Expr, HashMap<Symbol, Value>)> {
    let n = u.int_in_range(0_u32..=3)?;
    let mut env_types = Vec::new();
    for k in 0..n {
        env_types.push((Symbol(k), arb_type(u)?));
    }
    let want = arb_type(u)?;
    let expr = arb_expr(u, &env_types, want, MAX_DEPTH)?;
    let mut env = HashMap::new();
    for (s, t) in &env_types {
        env.insert(*s, arb_value(u, *t)?);
    }
    Ok((expr, env))
}

/// Generates a random expression and environment, then asserts the WASM tier
/// agrees with the interpreter oracle. Panics on divergence.
///
/// # Errors
///
/// Returns an [`arbitrary::Error`] only if the byte source is exhausted.
///
/// # Panics
///
/// Panics if the two expression backends produce different results.
pub fn differential_expr(u: &mut Unstructured) -> Result<()> {
    let (expr, env) = arb_expr_and_env(u)?;
    let via_interp = expr.eval(&env);
    let Ok(mut wasm) = WasmEval::new() else {
        return Ok(());
    };
    let via_wasm = wasm.eval_expr(&expr, &env);
    match (via_interp, via_wasm) {
        (Ok(a), Ok(b)) => {
            assert_eq!(a, b, "interp/wasm disagree on {expr:?} with {env:?}");
        }
        (Err(_), Err(_)) => {}
        (a, b) => panic!("backend divergence on {expr:?} with {env:?}: interp={a:?} wasm={b:?}"),
    }
    Ok(())
}

// ----- program generation --------------------------------------------------

struct RelSpec {
    name: String,
    schema: Vec<Type>,
    is_edb: bool,
}

fn arb_specs(u: &mut Unstructured) -> Result<Vec<RelSpec>> {
    let n_rel = u.int_in_range(2_usize..=4)?;
    let mut specs = Vec::with_capacity(n_rel);
    for i in 0..n_rel {
        let arity = u.int_in_range(1_usize..=2)?;
        let mut schema = Vec::with_capacity(arity);
        for _ in 0..arity {
            schema.push(arb_type(u)?);
        }
        specs.push(RelSpec {
            name: format!("r{i}"),
            schema,
            is_edb: false,
        });
    }
    // The first relation is always EDB; the rest are random, but ensure at
    // least one IDB relation exists so there is something to derive.
    specs[0].is_edb = true;
    for spec in specs.iter_mut().skip(1) {
        spec.is_edb = u.arbitrary()?;
    }
    if specs.iter().all(|s| s.is_edb) {
        let last = specs.len() - 1;
        specs[last].is_edb = false;
    }
    Ok(specs)
}

fn arb_body_atom(
    u: &mut Unstructured,
    spec: &RelSpec,
    bound: &mut Vec<(Symbol, Type)>,
    next_var: &mut u32,
    allow_bind: bool,
) -> Result<Atom> {
    let mut args = Vec::with_capacity(spec.schema.len());
    for &t in &spec.schema {
        let existing: Vec<Symbol> = bound
            .iter()
            .filter(|(_, bt)| *bt == t)
            .map(|(s, _)| *s)
            .collect();
        let arg = match u.int_in_range(0_u8..=3)? {
            0 if allow_bind => {
                let s = Symbol(*next_var);
                *next_var += 1;
                bound.push((s, t));
                Arg::Var(s)
            }
            1 if !existing.is_empty() => {
                let idx = u.choose_index(existing.len())?;
                Arg::Var(existing[idx])
            }
            2 => Arg::Lit(arb_value(u, t)?),
            _ => Arg::Wildcard,
        };
        args.push(arg);
    }
    Ok(Atom {
        relation: spec.name.clone(),
        args,
    })
}

fn head_args(u: &mut Unstructured, schema: &[Type], bound: &[(Symbol, Type)]) -> Result<Vec<Expr>> {
    let mut args = Vec::with_capacity(schema.len());
    for &t in schema {
        let cands: Vec<Symbol> = bound
            .iter()
            .filter(|(_, bt)| *bt == t)
            .map(|(s, _)| *s)
            .collect();
        if !cands.is_empty() && u.arbitrary()? {
            let idx = u.choose_index(cands.len())?;
            args.push(Expr::Var(cands[idx]));
        } else {
            // A literal head argument keeps the active domain finite, so the
            // fixed point always terminates regardless of the generated rules.
            args.push(Expr::Lit(arb_value(u, t)?));
        }
    }
    Ok(args)
}

fn maybe_aggregate(
    u: &mut Unstructured,
    specs: &[RelSpec],
    head_idx: usize,
    bound: &mut Vec<(Symbol, Type)>,
    next_var: &mut u32,
) -> Result<Option<BodyClause>> {
    if head_idx == 0 || !u.ratio(1_u8, 4_u8)? {
        return Ok(None);
    }
    let source_idx = u.int_in_range(0..=head_idx - 1)?;
    let source = &specs[source_idx];
    let Some(col) = source.schema.iter().position(|t| *t == Type::Int) else {
        return Ok(None);
    };
    let local = Symbol(*next_var);
    *next_var += 1;
    let mut sargs = vec![Arg::Wildcard; source.schema.len()];
    sargs[col] = Arg::Var(local);
    let func = *u.choose(&[AggFunc::Count, AggFunc::Sum, AggFunc::Min, AggFunc::Max])?;
    let output = Symbol(*next_var);
    *next_var += 1;
    bound.push((output, Type::Int));
    let arg = if func == AggFunc::Count {
        None
    } else {
        Some(Expr::Var(local))
    };
    Ok(Some(BodyClause::Aggregate(Aggregate {
        output,
        func,
        arg,
        source: Atom {
            relation: source.name.clone(),
            args: sargs,
        },
    })))
}

fn arb_rule(u: &mut Unstructured, specs: &[RelSpec], head_idx: usize) -> Result<Rule> {
    let mut bound: Vec<(Symbol, Type)> = Vec::new();
    let mut next_var = 0_u32;
    let mut body = Vec::new();

    for _ in 0..u.int_in_range(1_usize..=2)? {
        let ri = u.int_in_range(0..=specs.len() - 1)?;
        let atom = arb_body_atom(u, &specs[ri], &mut bound, &mut next_var, true)?;
        body.push(BodyClause::Positive(atom));
    }

    // Negation only over strictly-lower-indexed relations keeps the program
    // stratifiable by construction.
    if head_idx > 0 && u.ratio(1_u8, 3_u8)? {
        let ri = u.int_in_range(0..=head_idx - 1)?;
        let atom = arb_body_atom(u, &specs[ri], &mut bound, &mut next_var, false)?;
        body.push(BodyClause::Negative(atom));
    }

    if let Some(agg) = maybe_aggregate(u, specs, head_idx, &mut bound, &mut next_var)? {
        body.push(agg);
    }

    if u.ratio(1_u8, 3_u8)? {
        body.push(BodyClause::Condition(arb_expr(u, &bound, Type::Bool, 3)?));
    }

    let args = head_args(u, &specs[head_idx].schema, &bound)?;
    Ok(Rule {
        heads: vec![HeadAtom {
            relation: specs[head_idx].name.clone(),
            args,
        }],
        body,
    })
}

fn arb_program(u: &mut Unstructured) -> Result<(Program, Facts)> {
    let specs = arb_specs(u)?;
    let relations: Vec<RelationDecl> = specs
        .iter()
        .map(|s| RelationDecl {
            name: s.name.clone(),
            schema: s.schema.clone(),
            kind: RelationKind::Relation,
        })
        .collect();

    let mut rules = Vec::new();
    for (i, spec) in specs.iter().enumerate() {
        if spec.is_edb {
            continue;
        }
        for _ in 0..u.int_in_range(1_usize..=2)? {
            rules.push(arb_rule(u, &specs, i)?);
        }
    }

    let mut facts = Vec::new();
    for spec in &specs {
        if !spec.is_edb {
            continue;
        }
        for _ in 0..u.int_in_range(0_usize..=6)? {
            let mut tuple = Vec::with_capacity(spec.schema.len());
            for &t in &spec.schema {
                tuple.push(arb_value(u, t)?);
            }
            facts.push((spec.name.clone(), tuple));
        }
    }

    Ok((Program { relations, rules }, facts))
}

fn run_with(
    program: &Program,
    facts: &Facts,
    evaluator: &mut dyn ExprEval,
) -> std::result::Result<Database, EvalError> {
    let mut db = Database::new(program);
    for (relation, tuple) in facts {
        // Generated facts always match their relation's arity.
        let _ = db.insert(relation, tuple.clone());
    }
    eval::run(program, &mut db, evaluator)?;
    Ok(db)
}

/// Generates a random stratifiable program and facts, then asserts the
/// WASM-backed engine agrees with the interpreter-backed engine on every
/// relation. Panics on divergence.
///
/// # Errors
///
/// Returns an [`arbitrary::Error`] only if the byte source is exhausted.
///
/// # Panics
///
/// Panics if the two backends derive different relations, or if one fails while
/// the other succeeds.
pub fn differential_program(u: &mut Unstructured) -> Result<()> {
    let (program, facts) = arb_program(u)?;
    let via_interp = run_with(&program, &facts, &mut Interpreter);
    let Ok(mut wasm) = WasmEval::new() else {
        return Ok(());
    };
    let via_wasm = run_with(&program, &facts, &mut wasm);
    match (via_interp, via_wasm) {
        (Ok(d1), Ok(d2)) => {
            for r in &program.relations {
                let a: BTreeSet<Vec<Value>> = d1.tuples(&r.name).into_iter().collect();
                let b: BTreeSet<Vec<Value>> = d2.tuples(&r.name).into_iter().collect();
                assert_eq!(a, b, "relation `{}` diverged for {program:?}", r.name);
            }
        }
        (Err(_), Err(_)) => {}
        (a, b) => panic!(
            "backend divergence: interp={:?} wasm={:?} for {program:?}",
            a.err(),
            b.err()
        ),
    }
    Ok(())
}

// ----- fact generators for the macro fact-fuzzing layer --------------------

/// Generates up to `max_len` integer pairs in `[lo, hi]`, for fuzzing the EDB
/// of two-column fixtures (e.g. `edge`) against the `ascent!` macro.
///
/// # Errors
///
/// Returns an [`arbitrary::Error`] only if the byte source is exhausted.
pub fn arb_pairs(
    u: &mut Unstructured,
    max_len: usize,
    lo: i64,
    hi: i64,
) -> Result<Vec<(i64, i64)>> {
    let n = u.int_in_range(0..=max_len)?;
    let mut v = Vec::with_capacity(n);
    for _ in 0..n {
        v.push((u.int_in_range(lo..=hi)?, u.int_in_range(lo..=hi)?));
    }
    Ok(v)
}

/// Generates up to `max_len` integers in `[lo, hi]`, for fuzzing single-column
/// fixtures (e.g. `number`).
///
/// # Errors
///
/// Returns an [`arbitrary::Error`] only if the byte source is exhausted.
pub fn arb_singletons(u: &mut Unstructured, max_len: usize, lo: i64, hi: i64) -> Result<Vec<i64>> {
    let n = u.int_in_range(0..=max_len)?;
    let mut v = Vec::with_capacity(n);
    for _ in 0..n {
        v.push(u.int_in_range(lo..=hi)?);
    }
    Ok(v)
}

/// Generates up to `max_len` integer triples in `[lo, hi]`, for fuzzing
/// three-column fixtures (e.g. `point`, weighted `edge`).
///
/// # Errors
///
/// Returns an [`arbitrary::Error`] only if the byte source is exhausted.
pub fn arb_triples(
    u: &mut Unstructured,
    max_len: usize,
    lo: i64,
    hi: i64,
) -> Result<Vec<(i64, i64, i64)>> {
    let n = u.int_in_range(0..=max_len)?;
    let mut v = Vec::with_capacity(n);
    for _ in 0..n {
        v.push((
            u.int_in_range(lo..=hi)?,
            u.int_in_range(lo..=hi)?,
            u.int_in_range(lo..=hi)?,
        ));
    }
    Ok(v)
}
